name: Deploy React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Reinstall Rollup
        run: |
          npm uninstall rollup
          npm install rollup

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
            echo "⚠️ Build failed or dist/ directory is empty. Skipping deployment."
            exit 1
          fi

      - name: Deploy to server
        if: success()
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r dist/* $USER@$HOST:/var/www/appGrantt/dist
          ssh -i private_key.pem $USER@$HOST "sudo systemctl restart nginx"
          rm private_key.pem


