name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21 # Especifica la versión 21 de Node.js

      - name: Install dependencies
        run: npm ci

      - name: Reinstall Rollup
        run: |
          npm uninstall rollup
          npm install rollup --save-dev

      - name: Build project
        run: |
          npm run build
          if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
            echo "⚠️ Build failed or dist/ directory is empty. Skipping deployment."
            exit 1
          fi

      - name: Install sshpass (for password-based SSH)
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        if: success()
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Copiar los archivos al servidor usando sshpass
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r dist/* $USER@$HOST:/var/www/appGrantt/dist

          # Reiniciar Nginx en el servidor usando sshpass
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST "sudo systemctl restart nginx"

